import React, { useState } from 'react';
import { Bookmark, Trash2, Printer, Compass, ArrowRight, ExternalLink, Sparkles } from 'lucide-react';
import { BRAND_CONFIG } from '../../config/brand.ts';

interface SavedReadingsTabProps {
  savedReadings: any[];
  onDeleteReading: (id: string) => void;
  onNavigateToLifeArea: () => void;
  onNavigateToChat: () => void;
}

export const SavedReadingsTab: React.FC<SavedReadingsTabProps> = ({
  savedReadings,
  onDeleteReading,
  onNavigateToLifeArea,
  onNavigateToChat,
}) => {
  const [selectedReading, setSelectedReading] = useState<any | null>(null);

  const handlePrint = (reading: any) => {
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;

    printWindow.document.write(`
      <html>
        <head>
          <title>${reading.title} - ${BRAND_CONFIG.BRAND_NAME}</title>
          <style>
            body { font-family: Georgia, serif; line-height: 1.6; padding: 40px; color: #111; }
            h1 { font-size: 24px; color: #222; border-bottom: 2px solid #888; padding-bottom: 8px; }
            .meta { font-size: 13px; color: #666; margin-bottom: 24px; }
            .content { font-size: 15px; }
            .footer { margin-top: 50px; font-size: 12px; color: #777; border-top: 1px solid #ccc; padding-top: 12px; }
          </style>
        </head>
        <body>
          <h1>${reading.title}</h1>
          <div class="meta">
            Consultation with ${BRAND_CONFIG.ASTROLOGER_NAME} · ${new Date(reading.savedAt).toLocaleDateString()}
          </div>
          <div class="content">
            <p>${reading.summary}</p>
            <div>${reading.fullContent}</div>
          </div>
          <div class="footer">
            Generated by ${BRAND_CONFIG.BRAND_NAME} Vedic Astrology Platform.
          </div>
        </body>
      </html>
    `);
    printWindow.document.close();
    printWindow.focus();
    printWindow.print();
  };

  return (
    <div className="space-y-6">
      <div className="border-b border-[#1E2536] pb-4 flex items-center justify-between">
        <div>
          <h2 className="font-cinzel text-xl sm:text-2xl font-bold text-[#F4EFE6] mb-1">
            Saved Astrological Readings
          </h2>
          <p className="text-xs text-[#8E97AB]">
            Your collection of personal readings, insights, and dialogues with {BRAND_CONFIG.ASTROLOGER_NAME}
          </p>
        </div>
        <div className="text-xs text-[#B89647] font-semibold">
          {savedReadings.length} {savedReadings.length === 1 ? 'Reading' : 'Readings'} Saved
        </div>
      </div>

      {savedReadings.length === 0 ? (
        <div className="bg-[#0C1019] border border-[#1E2536] rounded-xl p-12 text-center max-w-lg mx-auto space-y-4">
          <Bookmark className="h-10 w-10 text-[#B89647]/50 mx-auto" />
          <h3 className="font-cinzel text-base font-semibold text-[#F0E6D2]">
            No Saved Readings Yet
          </h3>
          <p className="text-xs text-[#8E97AB] leading-relaxed">
            You can bookmark key insights, category deep-dives (Career, Love, Marriage, Money), or meaningful dialogue responses from Acharya Arya to review here anytime.
          </p>
          <div className="flex items-center justify-center gap-3 pt-2">
            <button
              onClick={onNavigateToLifeArea}
              className="px-4 py-2 bg-[#141A28] hover:bg-[#1E2638] text-xs font-medium text-[#F0E6D2] border border-[#273248] rounded transition-colors"
            >
              Explore Life Dimensions
            </button>
            <button
              onClick={onNavigateToChat}
              className="px-4 py-2 bg-[#B89647] hover:bg-[#C9A654] text-xs font-semibold text-[#0A0D14] rounded transition-colors"
            >
              Ask Acharya Arya
            </button>
          </div>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {savedReadings.map((reading) => (
            <div
              key={reading.id}
              className="bg-[#0F1420] border border-[#20283A] hover:border-[#38435C] p-5 rounded-lg flex flex-col justify-between transition-colors space-y-3"
            >
              <div>
                <div className="flex items-center justify-between mb-2">
                  <span className="text-[10px] uppercase tracking-wider text-[#B89647] font-semibold">
                    Category: {reading.category}
                  </span>
                  <span className="text-[10px] text-[#697387]">
                    {new Date(reading.savedAt).toLocaleDateString()}
                  </span>
                </div>
                <h4 className="font-cinzel text-sm font-bold text-[#F4EFE6] mb-2">
                  {reading.title}
                </h4>
                <p className="text-xs text-[#8E97AB] leading-relaxed line-clamp-3">
                  {reading.summary}
                </p>
              </div>

              <div className="flex items-center justify-between pt-3 border-t border-[#181F2F] text-xs">
                <button
                  onClick={() => setSelectedReading(reading)}
                  className="text-[#DFCA93] hover:text-[#FFFFFF] font-medium flex items-center gap-1"
                >
                  <span>View Full Reading</span>
                  <ArrowRight className="h-3 w-3" />
                </button>

                <div className="flex items-center gap-2">
                  <button
                    onClick={() => handlePrint(reading)}
                    className="p-1.5 text-[#7E889D] hover:text-[#FFFFFF] hover:bg-[#1A2130] rounded transition-colors"
                    title="Print reading"
                  >
                    <Printer className="h-3.5 w-3.5" />
                  </button>
                  <button
                    onClick={() => onDeleteReading(reading.id)}
                    className="p-1.5 text-[#7E889D] hover:text-[#FF7A85] hover:bg-[#2D1619] rounded transition-colors"
                    title="Delete reading"
                  >
                    <Trash2 className="h-3.5 w-3.5" />
                  </button>
                </div>
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Full Reading Modal View */}
      {selectedReading && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-[#05070B]/80 backdrop-blur-md">
          <div className="w-full max-w-2xl bg-[#0E131E] border border-[#242D40] rounded-xl shadow-2xl max-h-[85vh] flex flex-col overflow-hidden">
            <div className="flex items-center justify-between px-6 py-4 border-b border-[#1E2536] bg-[#0A0D15]">
              <div>
                <span className="text-[10px] text-[#B89647] font-semibold uppercase tracking-wider">
                  Saved Astrological Record
                </span>
                <h3 className="font-cinzel text-base font-bold text-[#F4EFE6]">
                  {selectedReading.title}
                </h3>
              </div>
              <button
                onClick={() => setSelectedReading(null)}
                className="text-[#788296] hover:text-[#FFFFFF]"
              >
                ✕
              </button>
            </div>

            <div className="p-6 overflow-y-auto space-y-4 text-xs sm:text-sm text-[#D8DFEE] leading-relaxed">
              <div className="bg-[#141A28] p-3.5 rounded border border-[#222B3D] text-xs text-[#A2ACBF]">
                {selectedReading.summary}
              </div>

              <div className="whitespace-pre-wrap font-cormorant text-base sm:text-lg text-[#CBD4E6] leading-relaxed">
                {selectedReading.fullContent}
              </div>
            </div>

            <div className="flex items-center justify-between px-6 py-3 border-t border-[#1E2536] bg-[#0A0D15]">
              <span className="text-[11px] text-[#6F788B]">
                Saved on {new Date(selectedReading.savedAt).toLocaleString()}
              </span>
              <button
                onClick={() => handlePrint(selectedReading)}
                className="flex items-center gap-1.5 px-3 py-1.5 bg-[#B89647] text-[#0A0D14] text-xs font-semibold rounded hover:bg-[#C9A654] transition-colors"
              >
                <Printer className="h-3.5 w-3.5" />
                <span>Print / Export PDF</span>
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
